apiVersion: v1
kind: Secret
metadata:
  name:	secret-key
  namespace: {{ required "Namespace is required!" .Values.global.namespace }}
type: Opaque
data:
  secret-key: {{ required "Django secret key is required!" .Values.django.secret_key | b64enc }}
