apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch-master
  name: elasticsearch-master
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-master
  template:
    metadata:
      labels:
        app: elasticsearch-master
    spec:
      containers:
        - name: elasticsearch-master
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
          imagePullPolicy: IfNotPresent
          env:
          - name: discovery.zen.ping.unicast.hosts
            value: elasticsearch-data,elasticsearch-master
          - name: node.name
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: cluster.name
            value: elk
          - name: node.data
            value: "false"
          - name: node.master
            value: "true"
          - name: node.ingest
            value: "false"
          - name: network.host
            value: "0.0.0.0"
          - name: bootstrap.memory_lock
            value: "false"

          volumeMounts:
          - name: storage-master
            mountPath: /usr/share/elasticsearch/data

          ports:
          - containerPort: 9300
            name: transport
            protocol: TCP

          resources:
            {{- toYaml .Values.elastic_master_resources | nindent 12 }}

      initContainers:
        - name: init-sysctl
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.elastic_init_resources | nindent 12 }}

        - name: fix-the-volume-permission
          image: busybox
          command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            privileged: true
          volumeMounts:
            - name: storage-master
              mountPath: /usr/share/elasticsearch/data
          resources:
            {{- toYaml .Values.elastic_init_resources | nindent 12 }}

        - name: increase-the-ulimit
          image: busybox
          command: ['sh', '-c', 'ulimit -n 65536']
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.elastic_init_resources | nindent 12 }}

      volumes:
      - name: storage-master
        persistentVolumeClaim:
          claimName: elasticsearch-master-pvc

      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ required "Namespace is required!" .Values.namespace }}
  name: elasticsearch-master
  labels:
    app: elasticsearch-master
spec:
  clusterIP: None
  selector:
    app: elasticsearch-master
  ports:
  - name: transport
    port: 9300