apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-pv-guts
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/elasticsearch/master"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-master-pvc
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: elasticsearch-master-pv-guts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data-pv-guts
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-pvc
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: elasticsearch-data-pv-guts
---    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-ingest-pv-guts
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/elasticsearch/ingest"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-ingest-pvc
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: elasticsearch-ingest-pv-guts
