apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  selector:
    app: kibana
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      nodePort: {{ required "A port between 30000 to 32767 is required!" .Values.service.nodeport }}
      port: 5601