apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ required "Namespace is required!" .Values.namespace }}
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:6.8.2
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch-ingest:9200

          resources:
            {{- toYaml .Values.kibana_resources | nindent 12 }}
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{ required "Namespace is required!" .Values.namespace }}
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana