# Generated by Django 3.2.11 on 2022-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
