apiVersion: v1
kind: Secret
metadata:
  name:	mariadb-pass
  namespace: {{ required "Namespace is required!" .Values.global.namespace }}
type: Opaque
data:
  root-password: {{ required "Database root password is required!" .Values.database.root_password | b64enc }}
  user-password: {{ required "Django secret key is required!" .Values.database.nonroot_password | b64enc }}
  exporter-data-source: ZXhwb3J0ZXI6WFhYWFhYWFhAKGxvY2FsaG9zdDozMzA2KS8=
