kind: ConfigMap
apiVersion: v1
metadata:
  name: query
  namespace: {{ required "Namespace is required!" .Values.global.namespace }}
data:
  create.sql: |
    CREATE USER 'exporter'@'%' IDENTIFIED BY 'XXXXXXXX';
    GRANT SELECT ON {{ .Values.global.database.name }}.* TO 'exporter'@'%';