---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ required "Namespace is required!" .Values.global.namespace }}
  labels:
    app: mariadb
spec:
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: exporter
      protocol: TCP
      port: 9104
      targetPort: 9104
  selector:
    app: mariadb
    tier: mariadb
  type: ClusterIP