apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:{{ .Values.alertmanager.image.tag | default "latest" }}
          imagePullPolicy: IfNotPresent
          args:
            - '--config.file=/etc/alertmanager/config.yml'
            - '--storage.path=/alertmanager'
          ports:
          - name: alertmanager
            containerPort: 9093
          volumeMounts:
          - name: config-volume
            mountPath: /etc/alertmanager
          - name: alertmanager
            mountPath: /alertmanager

          resources:
            {{- toYaml .Values.alertmanager_resources | nindent 12 }}

      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - name: alertmanager
        persistentVolumeClaim:
          claimName: alertmanager-data-pvc

      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  selector:
    app: alertmanager
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
