apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-data-pv
  labels:
    app: alertmanager
    name: alertmanager
    component: alertmanager
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/alertmanager"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data-pvc
  labels:
    app: alertmanager
    name: alertmanager
    component: alertmanager
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: alertmanager-data-pv