apiVersion: v1
kind: Secret
metadata:
  name: grafana-password
  labels:
    task: monitoring
    k8s-app: grafana
  namespace: {{ required "Namespace is required!" .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.grafana.password | b64enc }}
