apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: {{ required "Namespace is required!" .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: {{ required "Namespace is required!" .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
