apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: prometheus-server
  name: prometheus-server-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/prometheus"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus-server
  name: prometheus-claim
  namespace: {{ required "Namespace is required!" .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: prometheus-server-pv